
Welcome to Antergos !

To start the system input 'start' and press <Enter>


Available boot options:
harddisk                 - Boot From Hard Disk
start                    - Start Antergos Live System
skylake                  - Boot Troubleshooting For Intel Skylake Graphics
intel                    - Boot Troubleshooting For Intel Graphics (All)
nvidia                   - Boot Troubleshooting For NVIDIA Graphics
amd                      - Boot Troubleshooting For AMD Graphics
multi                    - Non-Graphical Boot
memtest                  - Run Memory Test
