Welcome to Antergos !

To start the system input 'start' and press <Enter>


Available boot options:
harddisk                 - Boot From Hard Disk
start                    - Start Antergos Live System
harddisk                 - Boot From Hard Disk
nvidia                   - Avoid using nouveau driver for nVidia cards
multi                    - Non-Graphical Boot
memtest                  - Run Memory Test
vesa                     - Use generic VESA driver
