Welcome to Antergos !

To start the system input 'start' and press <Enter>


Available boot options:
harddisk                 - Boot From Hard Disk
start                    - Start Antergos Live System
nvidia                   - Start Antergos Live System (nvidia fallback)
vesa                     - Start Antergos Live System (vesa fallback)
multi                    - Non-Graphical Boot
memtest                  - Run Memory Test
